### ISSUE TITLE
Unable to add tunnel from QR code on Android

### ISSUE THREAD

**Issue by amlamarra** [faicker/wg-config#1]
I've installed WireGuard on a Raspberry Pi 4 model b, followed the instructions here, generated a client, scanned the QR code, on the WireGuard Android app, but I get the error: `Unable to import tunnel: Unknown attribute in Interface`

The client `wg0.conf` file looks like this:

```
[Interface]
Address = 192.168.88.2/24
PrivateKey = <redacted>
Table = auto

[Peer]
PublicKey = LicRBQWLwJLwfGVqYaBYGFw3UTwMLSz8MuKzoJt1DE3=
AllowedIPs = 0.0.0.0/0
Endpoint = example.com:2000
```

I should also add that I tried importing the `wg0.conf` file. Same result.

**Comment by amlamarra** [comment]
Update: It didn't like the `Table = auto` line. When I removed that, I was able to add the tunnel.

**Comment by faicker** [comment]
Yes. The Table config is not supported in client.
latest master removed this.
If you want the clients to access internet, you must add some rules on server.
for example,
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s 192.168.88.0/24 -j MASQUERADE
And keep these rules persistent even reboot.
When generating the client conf, using the -r flag to enable all traffic to route to server.
